### ISSUE TITLE
Error al buscar usuario 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#100]
http://192.168.0.19:8080/DeliveryGuide/GenerateDeliveryGuide?IdCustomer=84&IdSite=47&IdItemState=1&Message=Error%3A%20Usuario%20no%20encontrado%2C%20favor%20verifique%20los%20datos%20en%20intente%20nuevamente
![image](https://user-images.githubusercontent.com/131712561/235185651-ca8b9caf-7cfd-4c79-8cbf-b862112a6340.png)
Usuario: Operador Ventanilla
Al buscar un usuario registrado por los parametros contenedor, nombre y codigo interno funciona correctamente, pero si se busca por el parametro rut da error. Luego de haber salido ese error, si se intenta buscar un usuario por cualquier parametro saldra error.

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
