### ISSUE TITLE
El boton iniciar lectura muchas veces necesita mas de dos click para funcionar

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#103]
http://192.168.0.19:8080/ChangeState/TagReading
![image](https://user-images.githubusercontent.com/131712561/235217887-054c91e4-48ba-4664-a591-6419577774d9.png)
Usuario: Administrador

**Comment by mcanales2020** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
