### ISSUE TITLE
Al hacer lectura de tag no se realiza ni una acción 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#105]
http://192.168.0.19:8080/ProcessGuide/GenerateProcessGuide?IdCustomer=84&IdSite=47&IdDevice=1&IdAntenna=4&IdItemState=7&IdActionWorkflow=10
![image](https://user-images.githubusercontent.com/131712561/235239139-ddb99abd-c19a-4cf2-a6b7-8e6869fdd719.png)
Usuario: Operadorropa limpia

**Comment by mcanales2020** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
