### ISSUE TITLE
Error al asignar tag a un contenedor

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#109]
http://192.168.0.19:8080/ContainerDetail/AssignamentsNew?containerId=1%20&userId=6%20&pCode=721%20&containerDetailId=85%20&status=2%20&newContainer=false
![image](https://user-images.githubusercontent.com/131712561/235245220-e7475ca4-e716-4b10-9376-a7611f5c5f92.png)
Usuario: Administrador
Despues de leer el tag (no asignado) sale error y dice que el tag ya esta registrado

**Comment by mcanales2020** [comment]
Ese error aparece cuando el Tag que se lee no está asociado a ningún artículo

**Comment by jyoo98** [comment]
ese error me sale cuando intento asignar un tag (sin asignar) a un zipper

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
