### ISSUE TITLE
Boton cacelar operación deberia redirigir a otra pantalla 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#110]
http://192.168.0.19:8080/DeliveryGuide/GenerateDeliveryGuide?IdCustomer=84&IdSite=47&IdDevice=1&IdItemState=1&IdActionWorkflow=3&FromDashboard=True&IdAntenna=2
![image](https://user-images.githubusercontent.com/131712561/235674687-465402cf-fa30-4f1b-a53c-5e32bd044e47.png)
Usuario: Operador ventanilla.
Al buscar por parametro rut da error. Luego de ese error, al cancelar la operación, redirige a la pantalla de selección de cliente

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
