### ISSUE TITLE
Boton buscar redirige a pantalla de autenticación

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#111]
http://192.168.0.19:8080/WorkOrder/GenerateWOUserNew?IdCustomer=84&IdSite=47&IdItemState=4&IdDevice=1&IdAntenna=1&IdActionWorkflow=16
![image](https://user-images.githubusercontent.com/131712561/235748283-c1df1e52-e986-4392-90ec-44b3c66458ca.png)
![image](https://user-images.githubusercontent.com/131712561/235748334-489fe1f2-c7d6-4548-ad1c-906397d92ac1.png)
Usuario: Operador ventanilla
Al buscar un usuario registrado en el sistema por el parametro nombre, redirige a pantalla de autenticacón. Al buscar por los demas parametros funciona correctamente.

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
