### ISSUE TITLE
Boton agregar no realiza ninguna acción

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#112]
http://192.168.0.19:8080/WorkOrder/GenerateWOUserNew2?IdCustomer=84&IdSite=47&IdItemState=4&IdDevice=1&IdActionWorkflow=16&SearchByInternCode=3785
![image](https://user-images.githubusercontent.com/131712561/235749119-fe88c979-866d-4713-9b6f-63db43bee026.png)
Usuario: Operador ventanilla 
Al buscar un contenedor para hacer una devolución, el boton agregar no realiza ninguna acción.

**Comment by cbastiasv** [comment]
Resuelto
