### ISSUE TITLE
Error al finalizar operación

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#113]
http://192.168.0.19:8080/WorkOrder/GenerateWOUserNew2
![image](https://user-images.githubusercontent.com/131712561/235749708-b2000a6a-9758-4930-b449-9e3db5737b4f.png)
Usuario: Operador ventanilla
Al tratar de finalizar la operación, da error.

**Comment by mcanales2020** [comment]
Resuelto

**Comment by jyoo98** [comment]
El error persiste

**Comment by mcanales2020** [comment]
Resuelto

**Comment by jyoo98** [comment]
![image](https://github.com/mcanales2020/yagan/assets/131712561/82bbcd96-4bcf-4c6d-a266-8bd5a22062df)
Ahora solo se queda sin hacer nada

**Comment by jyoo98** [comment]
Revisado
