### ISSUE TITLE
Al iniciar lectura no pasa nada

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#114]
http://192.168.0.19:8080/ProcessGuide/GenerateProcessGuide?IdCustomer=84&IdSite=47&IdDevice=1&IdAntenna=4&IdItemState=7&IdActionWorkflow=10
![image](https://user-images.githubusercontent.com/131712561/235756719-53336b6b-7067-4c99-a135-bd6edc1d2721.png)
Usuario: Operador ropa limpia

**Comment by mcanales2020** [comment]
Resuelto
