### ISSUE TITLE
Al buscar contenedor por número fisico, no cabe número en el label

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#119]
http://192.168.0.19:8080/Preload/GeneratePreload?IdCustomer=84&IdSite=47&IdDevice=1&IdAntenna=1&IdItemState=5&IdActionWorkflow=4&FromDashboard=True
![image](https://user-images.githubusercontent.com/131712561/235969677-405f2bef-9d1c-4c31-bb93-27404be941b7.png)
Usuario: Administrador
Al escribir el número fisico de un contenedor zipper, solo caben 10 digitos. El número fisico de un tag contiene 16 digitos.

**Comment by cbastiasv** [comment]
Lo aumenté a 20 pero el número del TAG no es el mismo que el Número Físico de un contenedor

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
