### ISSUE TITLE
Al importar un articulo ya registrado, se guarda de todos modos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#121]
http://192.168.0.19:8080/Item/Items
![image](https://user-images.githubusercontent.com/131712561/235984006-fbb1209c-07bf-40ce-9ad3-2301c741c7ab.png)
Usuario: Administrador
El articulo queda duplicado

**Comment by cbastiasv** [comment]
No existen restricciones en cuanto a crear artículos. Los nombres de los artículos no son únicos así que el sistema no los considera como duplicados (son distintos porque tienen distinto id), aun cuanto el nombre, talla, color o cualquier otro atributo sea igual

**Comment by jyoo98** [comment]
![image](https://user-images.githubusercontent.com/131712561/236305039-fcb5361d-5566-46e2-be09-1744f41cabff.png)

AL crear un artículo directamente en la aplicación, no me permite tenerlo duplicado, pero importandolo si

**Comment by jpfuhrer** [comment]
Carlos, entiendo que se pueden crear mucha variedad de articulos, pero no estoy de acuerdo con que pueda duplicar el mismo articulo.. Lo que muestan antes es que cada vez que suba un archivo de plantilla, mismo ID, mismo nombre, se crea otra linea duplicada... Por favor revisar el caso... No deben haber articulos duplicados

**Comment by cbastiasv** [comment]
El sistema no permitirá agregar dos artículos con el mismo código mánager. El resto de atributos pueden repetirse pero el código mánager será único en la base de datos

**Comment by jyoo98** [comment]
Revisado
