### ISSUE TITLE
Error al crear usuario

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#122]
http://192.168.0.19:8080/User/Users
![image](https://user-images.githubusercontent.com/131712561/236010300-b521a174-bdb9-4479-a9df-d6eff5f59bc8.png)
Usuario: Administrador
Despues de eliminar a un usuario del sistema, al querer registrar al mismo usuario dice que ya esta registrado

**Comment by cbastiasv** [comment]
Ningún usuario (y la mayor parte de la data) es realmente eliminada, los datos existen en la base de datos pero no los ve el usuario por eso dice que el rut ya se encuentra registrado. 
Puedo dejarlo como está, puedo habilitar al usuario si encuentra el rut durante la carga masiva o puedo crear otro usuario con el mismo rut, pero en la base existirían dos usuarios con el mismo rut.

**Comment by jyoo98** [comment]
¿Podría haber entonces una opción de habilitar al usuario?

**Comment by cbastiasv** [comment]
> ¿Podría haber entonces una opción de habilitar al usuario?

Ok, Resuelto

**Comment by jyoo98** [comment]
Revisado
