### ISSUE TITLE
Error al tratar de desvincular un articulo

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#124]
http://192.168.0.19:8080/Item/LinkItem2?IdUser=10
![image](https://user-images.githubusercontent.com/131712561/236022766-e04f09a1-70b8-49fa-b16e-8ce5b30be552.png)
Usuario: Administrador

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
