### ISSUE TITLE
Error al hacer click en vida útil de artículos 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#130]
http://192.168.0.19:8080/Report/ItemsWashes
![image](https://user-images.githubusercontent.com/131712561/236261453-da9c2826-2d30-441b-b1bf-ce571da5c062.png)
![image](https://user-images.githubusercontent.com/131712561/236261500-18722d5f-34b7-47c9-b562-5f7bbeab9a66.png)
Usuario: Manager

**Comment by cbastiasv** [comment]
Resuelto
