### ISSUE TITLE
Error al hacer click en estado de los tags

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#131]
http://192.168.0.19:8080/Report/ItemsWashes
![image](https://user-images.githubusercontent.com/131712561/236263211-df04840d-5447-4170-9dd0-0fb4d15f262b.png)
![image](https://user-images.githubusercontent.com/131712561/236263330-09a87a68-b88a-4be5-8f95-bba2f31b22a1.png)
Usuario: Manager

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
