### ISSUE TITLE
Guía de entrega redirige a pantalla de validación de datos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#144]
http://192.168.0.19:8080/DeliveryGuide/DeliveryGuides
![image](https://user-images.githubusercontent.com/131712561/236273383-1fabb4b1-6c5e-4025-8876-7176d71d0801.png)
Usuario: Operador botas

**Comment by cbastiasv** [comment]
Todos los accesos que están en el menú superior dirigen a la vista de selección de datos, solo los accesos directos dirigen a la operación en sí porque estos ya tienen configurado el dispositivo, destino, cliente/site con el cual se realiza la operación

**Comment by jpfuhrer** [comment]
No debe ser así. En imagen se aprecia que se entro como OPERADOR, no Adminsitrador. Por tanto la ruta debe estar definida y no preguntar. En caso contrario el operador de botas puede elegir cualquier antena y leer en cualquier parte. 

No es lo acordado y conversado.

**Comment by cbastiasv** [comment]
> No debe ser así. En imagen se aprecia que se entro como OPERADOR, no Adminsitrador. Por tanto la ruta debe estar definida y no preguntar. En caso contrario el operador de botas puede elegir cualquier antena y leer en cualquier parte.
> 
> No es lo acordado y conversado.

Cuando es operador solo le aparecen los clientes/sites, destino, reader y antena que le fueron asignados y según el tipo de guía que seleccionó (entrega, orden de trabajo, etc.), no puede seleccionar cualquier cosa como lo hace el administrador. Si el operador tiene solo una opción, le aparece todo preseleccionado, si al operador, por ejemplo, pudiera usar más de una antena (porque le fue asignada mas de una en el flujo de trabajo) podría seleccionar que antena quiere usar.

**Comment by jyoo98** [comment]
Revisado
