### ISSUE TITLE
Error al hacer click en vida útil de artículos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#149]
http://192.168.0.19:8080/Report/ItemsWashes
![image](https://user-images.githubusercontent.com/131712561/236293893-de8af29c-418b-48c4-91a4-9e3fca947ddc.png)
![image](https://user-images.githubusercontent.com/131712561/236293919-bc024045-d65f-4541-a1f1-d4106da5e048.png)
Usuario: Lectura

**Comment by cbastiasv** [comment]
Resuelto
