### ISSUE TITLE
No se agrega acceso directo de un operario en el dashboard 

### ISSUE THREAD

**Issue by LgVitali** [mcanales2020/yagan#15]
![image](https://user-images.githubusercontent.com/125584994/221863635-a1e19b69-10c7-442d-b1ea-bf8c1f1011ec.png)

**Comment by LgVitali** [comment]
Se creo operario ar-bot1 , se agrego el acceso a botas, se coloco el acceso directo y no apareció en el dashboard de la sesión del usuario ar-bot1.

**Comment by LgVitali** [comment]
Pero es crear un acceso directo para entrega, como ejemplo si se necesita hacer una entrega en puestos sin antena ya existe la opción de entregar sin tag. 

Pero de todos modos probare lo comentado y comento.

**Comment by LgVitali** [comment]
> falta asignar antena
> 
> ![imagen](https://user-images.githubusercontent.com/109356244/222438297-8faab7a5-a7f3-4e46-96aa-b0ad746069a5.png)

Podrían indicarme como llegar a esa pestaña de opciones.

**Comment by LgVitali** [comment]
Listo es flujo de trabajo / Ariztía / acción / tuerca del operador / dispositivo / al mas de asignar. estamos probando pero comprendido, seria bueno dejar la opciones para llegar a las ventanas.

**Comment by H-ADASME563** [comment]
Entramos al flujo de trabajo que creamos, y en el apartado de "Acciones" hay que presionar el engranaje de configuración

![image](https://user-images.githubusercontent.com/109356244/222454999-033cb446-0fa5-4e68-8012-8d1570f56e85.png)

Aqui nos encontraremos con una vista sin información, asi que primero hay que escoger al operador, que fue asignado para esa operación, en la lista desplegable de "Operador" y después abajo nos saldra la antena y un botón con el signo "+", hay que presionar en el + para asignar la antena al operador

![image](https://user-images.githubusercontent.com/109356244/222455657-d9b6f577-1a8f-4525-ade3-d60eb8afb5a7.png)

**Comment by jpfuhrer** [comment]
Mismo caso anterior... que pasa en lugares donde no se utiliza TAG ni antenas y es huella digital y registro manual de entrega zipper, toallas, etc.

**Comment by cbastiasv** [comment]
Crea el acceso directo pero no permite ingresar a el. Aparece Error al Procesar

**Comment by cbastiasv** [comment]
Corregido
