### ISSUE TITLE
Error al hacer click en estado de los tags

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#150]
http://192.168.0.19:8080/Report/ItemsWashes
![image](https://user-images.githubusercontent.com/131712561/236294172-50e03354-f587-4a4e-b5ee-6ce320e7d186.png)
![image](https://user-images.githubusercontent.com/131712561/236294187-51d46036-f2c8-4bf8-8abd-ee2dd2b9dcd0.png)
Usuario: Lectura

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
