### ISSUE TITLE
Lectura lenta al realizar orden de trabajo

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#172]
http://192.168.0.19:8080/WorkOrder/GenerateWorkOrder
![image](https://github.com/mcanales2020/yagan/assets/131712561/ee2f7c59-814d-4322-9e01-42a63cc90199)
Usuario: Administrador, Operador 
Al realizar una orden de trabajo, tarda mucho en leer los tags (450 tags) y los lee uno por uno. Al finalizar la operación la aplicación de pone lenta, no muestra la cantidad total de tags leidos y al cancelar la operación tarda en cargar.

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
