### ISSUE TITLE
Lectura lenta al realizar guía de proceso

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#173]
http://192.168.0.19:8080/ProcessGuide/GenerateProcessGuide
![image](https://github.com/mcanales2020/yagan/assets/131712561/c20a3d7b-1f4a-4aac-a173-39e8e5c8d7f7)
Usuario: Administrador, Operador 
Al finalizar operación, la aplicación se queda lenta y no muestra la cantidad total de tags leidos

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
