### ISSUE TITLE
Al tratar de importar zippers por carga masiva da error

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#174]
http://192.168.0.19:8080/ContainerDetail/ContainerDetails?IdContainer=1
![image](https://github.com/mcanales2020/yagan/assets/131712561/6214a677-a4b1-4077-8f81-42587d172e14)
![image](https://github.com/mcanales2020/yagan/assets/131712561/6f470612-e7b4-4ba1-8510-fa0ba603a925)
Usuario: Administrador 
Cuando subo el archivo csv dice que el archivo es incorrecto.

**Comment by sebastianmtralcal** [comment]
Asignado  Sebastián

**Comment by sebastianmtralcal** [comment]
No se logra replicar el error, se solicita adjuntar el archivo que arroja el error

**Comment by jyoo98** [comment]
[Plantilla Importar Detalle Contenedor (1).csv](https://github.com/mcanales2020/yagan/files/11548524/Plantilla.Importar.Detalle.Contenedor.1.csv)

**Comment by sebastianmtralcal** [comment]
Problema resuelto

**Comment by jyoo98** [comment]
![image](https://github.com/mcanales2020/yagan/assets/131712561/b4f50b77-863a-46b9-a715-2b3c3834db26)
me sale un error no especificado

**Comment by sebastianmtralcal** [comment]
Problema resuelto

**Comment by jyoo98** [comment]
Revisado
