### ISSUE TITLE
Los artículos no cambian de estado al hacer entrega de zipper 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#177]
![image](https://github.com/mcanales2020/yagan/assets/131712561/088304b0-838b-4b90-9ee1-476e07b6548f)

Luego de hacer una precarga, al hacer entrega de zipper por lectura de tag, los artículos precargados en el zipper no cambian de estado hacia con usuario. Cuando hago este circuito de manera manual no pasa esto, los artículos si cambian de estado hacia con usuario.
Usuario: Administrador, Operador

**Comment by sebastianmtralcal** [comment]
Asignado  Sebastián

**Comment by sebastianmtralcal** [comment]
Esto lo debe revisar Matias

**Comment by jyoo98** [comment]
Revisado
