### ISSUE TITLE
Permite vincular artículos no vinculables

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#178]
http://192.168.0.19:8080/Item/LinkItem2?IdUser=5%20&message=Los%20tag%20fueron%20asignados%20correctamente%20&success=true
![image](https://github.com/mcanales2020/yagan/assets/131712561/cc11949d-8833-4750-9aab-de759c79cdfd)
![image](https://github.com/mcanales2020/yagan/assets/131712561/47f337c1-6e61-4623-9842-a7e3054bc275)
Usuario: Administrador

**Comment by sebastianmtralcal** [comment]
Asignado  Sebastián

**Comment by sebastianmtralcal** [comment]
Problema resuelto
ejemplo usado : E2806894000050234C538975

**Comment by jyoo98** [comment]
¿Actualizaste la web?

**Comment by jyoo98** [comment]
Probe con el mismo tag y me sigue dejando vincular el artículo
![image](https://github.com/mcanales2020/yagan/assets/131712561/74516027-f8b3-4d0a-870a-c0de517ada65)
E2806894000050234C538975

**Comment by sebastianmtralcal** [comment]
lo hice manualmente y no deja validar cuando el articulo no es de vinculación permanente, favor indicar como es que se hace el ingreso para que el tag se vincule correctamente.

adjunto evidencia:
![image](https://github.com/mcanales2020/yagan/assets/86976515/09fa5b25-b281-4a49-9ee7-31a2cd119490)

**Comment by jyoo98** [comment]
Me parece que con la ultima se actualización se arreglo, ya no me deja vincularlo, pero no hay feedback

**Comment by sebastianmtralcal** [comment]
![image](https://github.com/mcanales2020/yagan/assets/86976515/64d5e2ce-60b4-428a-ac10-0b87b7b4c51a)

**Comment by jyoo98** [comment]
Las pruebas que estoy haciendo son con lectura de tag, tu lo estas haciendo de manera manual

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
revisado
