### ISSUE TITLE
Los reportes no se pueden descargar en formato pdf

### ISSUE THREAD

**Issue by LgVitali** [mcanales2020/yagan#18]
![image](https://user-images.githubusercontent.com/125584994/221872254-a2f1f51d-6162-4809-9e5f-ffb29211867c.png)

Los reportes como historiales clínicos solo están en formato CVS, pero por temas de reportes no se pueden realizar también en PDF?

**Comment by H-ADASME563** [comment]
En sow esta especificado que los reportes se descargan en CSV y los gráficos en formato PDF.
Además los reportes tienen varias columnas, en formato pdf no se apreciaría bien toda la información
