### ISSUE TITLE
Al presionar botón cancelar operación, redirige a pantalla de error 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#181]
http://192.168.0.19:8080/ChangeItem/GenerateChangeItems
![image](https://github.com/mcanales2020/yagan/assets/131712561/dfd5c4f0-d6b7-498f-a0e7-58cfbbd9f9e1)
![image](https://github.com/mcanales2020/yagan/assets/131712561/2008ab83-f92f-43ab-863f-d89162dc7825)
Usuario: Administrador

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
