### ISSUE TITLE
Botón iniciar lectura no realiza ninguna acción 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#182]
http://192.168.0.19:8080/ChangeItem/GenerateChangeItems
![image](https://github.com/mcanales2020/yagan/assets/131712561/c8f76824-9dff-4355-8582-d425a815acd0)
Usuario: Administrador
En cambio de artículo entregado, al presionar el botón iniciar lectura entrega (para cambiar artículos entregados), no realiza ninguna acción

**Comment by cbastiasv** [comment]
Resuelto

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
