### ISSUE TITLE
Al presionar ambos botones de lectura a la vez, la antena queda tomada

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#183]
http://192.168.0.19:8080/ChangeItem/GenerateChangeItems
![image](https://github.com/mcanales2020/yagan/assets/131712561/bcee51fe-8ce6-4f9e-a232-fb5c717997a5)
Usuario: Administrador 
En cambio de artículos entregado, al presionar simultaneamente ambos botones de lectura, la antena 1 queda tomada y la aplicación no realiza ninguna acción

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
