### ISSUE TITLE
El botón de iniciar lectura entrega debería estar bloqueado mientras iniciar lectura devolución este activo

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#184]
http://192.168.0.19:8080/ChangeItem/GenerateChangeItems
![image](https://github.com/mcanales2020/yagan/assets/131712561/abf30c46-6930-4bd0-a424-826210bff3c3)
Usuario: Administrador
Se pueden presionar ambos botones a la vez

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
