### ISSUE TITLE
El botón finalizar operación no tiene feedback

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#186]
http://192.168.0.19:8080/ChangeItem/GenerateChangeItems
![image](https://github.com/mcanales2020/yagan/assets/131712561/c9574b75-252f-4579-96d9-d39b7a2e1e67)
Usuario: Administrador

**Comment by jyoo98** [comment]
![image](https://github.com/mcanales2020/yagan/assets/131712561/a8310079-a4a4-4ffc-9ff3-73f375226d71)
ahora sale eso

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
