### ISSUE TITLE
Mal funcionamiento al entregar artículo pareado (guía de entrega)

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#187]
http://192.168.0.19:8080/DeliveryGuide/ShowDeliveryGuidesNew
![image](https://github.com/mcanales2020/yagan/assets/131712561/23fa91fa-7080-49e4-830c-713a0cf632ab)
![image](https://github.com/mcanales2020/yagan/assets/131712561/ddf990ac-c010-4217-8273-cd03714817be)
![image](https://github.com/mcanales2020/yagan/assets/131712561/3498e996-2015-43dd-ba60-6c3ce81e25ab)
![image](https://github.com/mcanales2020/yagan/assets/131712561/3f9d302a-f18f-4f9d-bbd7-e83835f8bebd)
![image](https://github.com/mcanales2020/yagan/assets/131712561/d08bf64f-2d1a-41a1-8ac2-3d97f30c962f)
![image](https://github.com/mcanales2020/yagan/assets/131712561/039f53ff-a882-46c8-83e4-22b29c2dbd28)
Usuario: Administrador, Operador
Al entregar un artículo pareado (Bota Blanca - 40), se requiere leer ambos tags (tags por cada bota) para que para que los dos tags cambien de estado hacia con usuario. Si solo se lee un tag, solo uno cambia de estado a con usuario, el otro tag queda en sala botas.
TAGS pareados usados en la prueba:
E2806894000040234C53E168
E2806894000050234C52CC19

**Comment by sebastianmtralcal** [comment]
![image](https://github.com/mcanales2020/yagan/assets/86976515/3676ef71-29fa-40b4-a4f8-81ecd3ed8375)

manualmente si lo hace

**Comment by sebastianmtralcal** [comment]
![image](https://github.com/mcanales2020/yagan/assets/86976515/dd3d2613-6c84-4aff-83f8-638c11ed7d59)

se replica mismo ejemplo en Yagan y manualmente funciona

**Comment by cbastiasv** [comment]
Resuelto (Se debe probar con lectura de tags)
