### ISSUE TITLE
Se queda cargando al tratar de subir un archivo .jpg

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#193]
http://192.168.0.19:8080/Item/Edit?IdItem=1
![image](https://github.com/mcanales2020/yagan/assets/131712561/e1958ce1-3ba1-4afe-bc1c-923aa5e83e33)
Usuario: Administrador 
Al editar o crear un nuevo artículo, al tratar de subir un archivo .jpg, la aplicación web se queda cargando

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
