### ISSUE TITLE
No se actualiza el estado en el reporte de lavados

### ISSUE THREAD

**Issue by LgVitali** [mcanales2020/yagan#20]
![image](https://user-images.githubusercontent.com/125584994/221876349-4d7bc7dc-e821-47a5-b189-2fb5e3122ad8.png)

Se realizaron los movimientos en el tag 1 de Usuario a Ropa sucia, luego se realizo el movimiento de ropa sucia a ropa limpia  para el tag 1 blusa. No se visualizo en en la sección reporte / lavado de artículos,  ningún movimiento.

**Comment by H-ADASME563** [comment]
De ropa sucia a ropa limpia es una GP, deben de editar la acción y apretar el check de Ingreso a lavandería

![image](https://user-images.githubusercontent.com/109356244/222444151-ef1bd95d-c42b-40de-a9a3-5a74f731473a.png)

**Comment by jpfuhrer** [comment]
se marco en proceso ropa sucia a ropa limpia y quedo contando. pero laas fechas estan raras
