### ISSUE TITLE
Falta de datos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#206]
http://192.168.0.19:8080/Report/ItemsInventory
![image](https://github.com/mcanales2020/yagan/assets/131712561/63de7a1f-b76a-47f2-a3e2-bd32633da142)
Usuario: Administrador
El encabezado de cada gráfico debería ser mas grande, y también hace falta que muestre el total de artículos por gráfico.

**Comment by sebastianmtralcal** [comment]
![image](https://github.com/mcanales2020/yagan/assets/86976515/39b9c05d-a430-4eb7-92f7-1d68de5565a5)
