### ISSUE TITLE
No me deja agregar dispositivos a una accion

### ISSUE THREAD

**Issue by LgVitali** [mcanales2020/yagan#21]
![image](https://user-images.githubusercontent.com/125584994/221878622-3b3b22ec-9a78-473f-8bf5-0f97be2fce1c.png)

No me permite agregar un dispositivo a una acción, en Flujo de Trabajo / Ariztia / Acción / Entrega Directa de Zipper. en el cual ya esta creado el dispositivo en mantenedores / dispositivo / Reader Sr.

**Comment by H-ADASME563** [comment]
En su mantenedor agregaron un Reader, en la ventana de agregar dispositivos aparecerán todos los dispositivos que no seas readers
