### ISSUE TITLE
Proceso: Asignar Artículo por lectura de tags

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#215]
http://192.168.0.19:8080/Item/AssignItem2?IdItem=8
![image](https://github.com/mcanales2020/yagan/assets/131712561/aed691e8-fb8b-411d-b5fc-b37575b383ce)

Usuario: Administrador.
Después de leer el tag, al finalizar da error y el tag no queda registrado

**Comment by mcanales2020** [comment]
Favor revisar

**Comment by jyoo98** [comment]
Revisado
