### ISSUE TITLE
Proceso: Vincular Artículo por lectura de tags

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#216]
http://192.168.0.19:8080/Item/LinkUnlinkItem?InternCode=721&IdCustomer=84&IdSite=47&glScann=0
![image](https://github.com/mcanales2020/yagan/assets/131712561/b0bcd6e0-a2e0-43a4-a652-acb5e9cb6c95)

Usuario: Administrador
Al darle click en iniciar lectura da error.

**Comment by mcanales2020** [comment]
Favor revisar

**Comment by jyoo98** [comment]
Revisado
