### ISSUE TITLE
Proceso: Orden de trabajo 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#217]
http://192.168.0.19:8080/WorkOrder/GenerateWOUserNew2
![image](https://github.com/mcanales2020/yagan/assets/131712561/ae87a197-25e8-4923-b1e1-e8c780f325d2)

Usuario: Administrador
En orden de trabajo por usuario, los botones iniciar lectura, pausar lectura, reiniciar lectura, cancelar operación, no realizan ninguna acción

**Comment by mcanales2020** [comment]
Favor revisar

**Comment by jyoo98** [comment]
revisado
