### ISSUE TITLE
Acceso directo: Ropa de camarines a lavandería 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#218]
![image](https://github.com/mcanales2020/yagan/assets/131712561/e4c78bb5-70c8-49ef-9455-e27257342581)

![image](https://github.com/mcanales2020/yagan/assets/131712561/d87c373f-e0d3-47c5-90ab-be407423a021)

Usuario: Operador Ropa sucia
al darle click a Ropa de camarines a lavandería masivo, me redirige a buscar por usuario

**Comment by sebastianmtralcal** [comment]
Solucionado

**Comment by jyoo98** [comment]
Revisado
