### ISSUE TITLE
GUIA DE ENTREGA - Me sigue preguntando por la antena

### ISSUE THREAD

**Issue by jpfuhrer** [mcanales2020/yagan#22]
Al establecer que el destino es con usuario (desde sala de Zipper), sigue preguntando por la antena, cuando esta definida que antena es.  Esto es porque estamos como administrador??  No debería pasar esto si entro como operario?

![image](https://user-images.githubusercontent.com/125582822/221878782-3f543400-ba11-405e-9352-285e5b6c2863.png)

**Comment by H-ADASME563** [comment]
Al estar con perfil administrador el sistema mostrará todas las antenas del reader
