### ISSUE TITLE
Asignar artículo por carga masiva 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#224]
http://192.168.0.19:8080/Item/AssignItem
![image](https://github.com/mcanales2020/yagan/assets/131712561/8272bf73-e2cd-42e2-8841-debb93cdb3ee)
![image](https://github.com/mcanales2020/yagan/assets/131712561/b950f342-5a9c-4daf-b1f3-00211c972ac2)
Usuario: Administrador 
Al tratar de asignar un artículo por carga masiva, al subir el archivo y lueog darle guardar, se queda cargando como se muestra en la imagen

**Comment by cbastiasv** [comment]
No pude replicar el error. Intenté cargar un archivo csv con los mismos datos y lo guardó sin problemas.
Agregué un catch en caso de que no pueda conectar al servidor (que es lo que probablemente pasó en este caso) u ocurra un error no controlado en este al validar o guardar los datos, así no queda cargando y muestra un mensaje de error.
