### ISSUE TITLE
Yagan Web: Error en guía de entrega con reconocimiento facial 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#227]
http://192.168.0.19:8080/DeliveryGuide/GenerateDeliveryGuide
![image](https://github.com/mcanales2020/yagan/assets/131712561/cb44ba21-5d33-4d59-9603-5f354c9e95b2)

Usuario: Administrador.
Al tratar de realizar una guía de entrega, tras hacer la lectura facial (con un usuario enrolado), el sistema arroja un error no encontrando el registro. Pruebas hechas con ambos HIK (grande y pequeño).

**Comment by sebastianmtralcal** [comment]
Favor probar nuevamente
