### ISSUE TITLE
Yagan App: Error al buscar usuario por contenedor 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#228]
https://github.com/mcanales2020/yagan/assets/131712561/99986638-cd2f-41d6-a087-a756180ec593

Al buscar al usuario por el número de su contenedor, lo muestra dos veces, no imposibilita el uso pero puede ser confuso.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado
