### ISSUE TITLE
Yagan App: Error al enviar reporte por correo

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#229]
https://github.com/mcanales2020/yagan/assets/131712561/767d460a-f6eb-45fc-9f78-8c4de72bdce9

En consulta de estado, al tratar de enviar el reporte por correo da error. Esto pasa con los 4 módulos superiores.

**Comment by mcanales2020** [comment]
Jae, no tiene permisos para escribir en la ruta el archivo pdf. 
La ruta es la siguiente: C:\inetpub\wwwroot\api\Uploads\ReportStatus\
Puedes setear con permisos de escritura?

**Comment by jyoo98** [comment]
Esa carpeta no existe en LAB-YAGAN

 



 

De: mcanales2020 ***@***.***> 
Enviado el: miércoles, 6 de septiembre de 2023 17:23
Para: mcanales2020/yagan ***@***.***>
CC: jyoo98 ***@***.***>; Author ***@***.***>
Asunto: Re: [mcanales2020/yagan] Yagan App: Error al enviar reporte por correo (Issue #229)

 

Jae, no tiene permisos para escribir en la ruta el archivo pdf.
La ruta es la siguiente: C:\inetpub\wwwroot\api\Uploads\ReportStatus
Puedes setear con permisos de escritura?

**Comment by jyoo98** [comment]
De: mcanales2020 ***@***.***> 
Enviado el: miércoles, 6 de septiembre de 2023 17:23
Para: mcanales2020/yagan ***@***.***>
CC: jyoo98 ***@***.***>; Author ***@***.***>
Asunto: Re: [mcanales2020/yagan] Yagan App: Error al enviar reporte por correo (Issue #229)

 

Jae, no tiene permisos para escribir en la ruta el archivo pdf.
La ruta es la siguiente: C:\inetpub\wwwroot\api\Uploads\ReportStatus
Puedes setear con permisos de escritura?
