### ISSUE TITLE
Yagan Web: Leer un TAG no registrado en el sistema reinicia la operación 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#230]
https://github.com/mcanales2020/yagan/assets/131712561/b6762ac7-5b1c-4449-9234-6111dce3cd1f

Usuario: Administrador 

Cuando se realiza una operación que requiera leer mas de un tag, si el sistema lee un tag que no conozca, reinicia la operación y no da la opción de borrar el TAG desconocido. Dicha situación provoca que no se pueda completar la operación.

**Comment by mcanales2020** [comment]
Esto es un requerimiento nuevo
