### ISSUE TITLE
Yagan App: Última lectura en la app no coincide con la web

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#231]
![Imagen de WhatsApp 2023-09-12 a las 11 37 39](https://github.com/mcanales2020/yagan/assets/131712561/c89cf76f-76a9-48d1-a627-fbc7ffc618e6)
![Imagen de WhatsApp 2023-09-12 a las 11 37 3](https://github.com/mcanales2020/yagan/assets/131712561/bb8de49f-34a6-4a69-8810-0cba80bc5a04)

Usuario: Administrador 
Las últimas lecturas del mismo TAG no coinciden entre la app y la web

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
revisado
