### ISSUE TITLE
Yagan App: Incluir mensaje en búsqueda de artículos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#232]
![image](https://github.com/mcanales2020/yagan/assets/131712561/de409a0e-407b-4315-8ced-6de8bd2230be)
Incluir mensaje de aviso para que el usuario sepa que mientras el número que aparezca en ventana sea de menor valor, es porque esta mas cerca del artículo que esta buscando, esto para que sea mas intuitivo.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
ok revisado
