### ISSUE TITLE
Yagan App: Error al buscar usuario para hacer vinculación de artículos 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#233]
https://github.com/mcanales2020/yagan/assets/131712561/753fe74c-7330-427d-b8f9-45345b0a8175

Al buscar al usuario para hacer una vinculación de artículos, muestra un mensaje diciendo sin resultados en la búsqueda. Esto puede resultar confuso, ya que, la búsqueda que se hizo inicialmente fue del usuario.
Cambiar el mensaje por algo que especifique que lo que no se encuentra son los artículos vinculados del usuario.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado
