### ISSUE TITLE
Yagan Web: Sin auto-enter

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#242]
https://github.com/mcanales2020/yagan/assets/131712561/36cff0c9-a104-4a64-9b01-89dc4bfa3796

Usuario: Operador Ropa Sucia, Operador ar-vent1, Administrador
al leer la tarjeta yagan no permite el auto-enter. Esto pasa con las ordenes de trabajo solamente.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado
