### ISSUE TITLE
Yagan Web: Error en Generar Orden de Trabajo 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#243]
https://github.com/mcanales2020/yagan/assets/131712561/265efff0-1d97-4aa1-a6e8-29b512402e87

Al tratar de hacer una orden de trabajo da error.
Usuario: Operador NES-Vent1

**Comment by jyoo98** [comment]
https://github.com/mcanales2020/yagan/assets/131712561/b79ff384-de78-4fb0-a114-78e2f4f26316

Actualización: Si pasa pero al leer la tarjeta no hace auto enter y si lo hago manual el botón buscar no hace nada.

**Comment by jyoo98** [comment]
https://github.com/mcanales2020/yagan/assets/131712561/26eed15c-48d6-49dd-8282-c0a08c5cfd3c

Actualización: Realiza la operación pero al final tira la pantalla de error

**Comment by jyoo98** [comment]
![Imagen de WhatsApp 2023-10-20 a las 09 07 36_2081a2cf](https://github.com/mcanales2020/yagan/assets/131712561/0f9116f4-8c59-42b4-8296-40e515fe8230)

Actualización: Da error al darle iniciar lectura.

**Comment by jyoo98** [comment]
![image](https://github.com/mcanales2020/yagan/assets/131712561/c7026aae-d76f-4f79-86c8-58b544871c0d)

![image](https://github.com/mcanales2020/yagan/assets/131712561/3f4092f6-8bba-4a2d-9a21-ef29df3d08a2)

Actualización: Como Operador NES-Vent4, al darle al botón nueva orden de trabajo, me redirige a la pantalla de selección de cliente y dispositivos, cuando debería redirigir directamente a la pantalla de búsqueda de usuario

**Comment by mcanales2020** [comment]
Corregido

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Actualización: ya no me da error pero el botón nueva orden de trabajo me redirige a la pantalla de lectura con el mismo usuario 

https://github.com/mcanales2020/yagan/assets/131712561/e95bf85a-624f-48dc-b354-3a7bf333a08d

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
revisado
