### ISSUE TITLE
Yagan Web: Botón Finalizar operación se bloquea

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#244]
https://github.com/mcanales2020/yagan/assets/131712561/27b4b0e0-1631-45fa-86d3-2c3e3be172f5

El botón finalizar operación se bloquea cuando uno pausa la lectura y luego la reinicia. 
Usuario: Administrador, Operador

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
![image](https://github.com/mcanales2020/yagan/assets/131712561/7ea6ba7e-b96b-4093-99f2-1177c76eeb47)

Actualización: Finalizar la lectura aparece error de desconexión.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado
