### ISSUE TITLE
Yagan Web: Error al agregar dispositivo.

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#245]
![image](https://github.com/mcanales2020/yagan/assets/131712561/35418361-7411-4678-a54d-3abe93139d84)

Al agregar un dispositivo de reconocimiento dactilar los parámetros mostrados no son los correctos para el dispositivo.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
revisado
