### ISSUE TITLE
Yagan Web: Enrolamiento de huellas dactilares

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#246]
https://github.com/mcanales2020/yagan/assets/131712561/4d36a11c-a52a-4e7e-858c-e06cbbd71d45

Al enrolar a un usuario por reconocimiento de huella dactilar no se guardan los datos

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado
