### ISSUE TITLE
Yagan Web: Mantenedor de dispositivos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#247]
![image](https://github.com/mcanales2020/yagan/assets/131712561/4e4025aa-f33f-488d-bd76-376d5e7de42c)

Al tratar de iniciar el listener del reconocimiento facial, da error de conexión.

**Comment by sebastianmtralcal** [comment]
![image](https://github.com/mcanales2020/yagan/assets/86976515/477dc3d6-0227-4b73-b49c-8b76d853e353)


se prueban ambos dispositivos quedando okay cada una de las conexiones, luego se procede a desconectar, donde tambien se muestra el funcionamiento.
![image](https://github.com/mcanales2020/yagan/assets/86976515/07f1b6d0-ea6b-43a4-b862-0c999931af0e)

![image](https://github.com/mcanales2020/yagan/assets/86976515/04fb8e76-6853-4d7e-ac52-66377e2e863a)

**Comment by jyoo98** [comment]
Revisado
