### ISSUE TITLE
Yagan Web: Error en reconocimiento de huellas dactilares

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#248]
https://github.com/mcanales2020/yagan/assets/131712561/a7292dc9-9890-4340-9ac9-b52e32b91669

Al realizar una operación que requiera de reconocimiento de huellas dactilares, no identifica al usuario a pesar de que esta enrolado.
Usuario: Administrador, Operador

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado
