### ISSUE TITLE
Yagan App: Error al sincronizar operaciones offline

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#249]
https://github.com/mcanales2020/yagan/assets/131712561/319d4d0b-571b-4b6b-9f1c-91c42316f0d9

![image](https://github.com/mcanales2020/yagan/assets/131712561/a5f5e3d0-79d6-4f12-b7ca-8dd4def51d6b)
Al sincronizar las operaciones offline en la app, al revisar en la web no aparece ninguna operación con el folio o con la fecha correspondiente.
N° Folio: 151699367313226

**Comment by jyoo98** [comment]
Actualización: Cuando se quiere hacer una orden de trabajo con internet da error.
![image](https://github.com/mcanales2020/yagan/assets/131712561/1370f47b-ca37-409e-b44e-c8e3c396d376)

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Ahora si se sincronizan las OT, pero las GE aunque la app este en modo offline funcionan como si estuviera siempre en modo online.


https://github.com/mcanales2020/yagan/assets/131712561/b72ec7d1-e8a9-4391-9428-03fb8737d0f9

![image](https://github.com/mcanales2020/yagan/assets/131712561/600cb2d3-2861-4230-bc55-732d985e87a9)

**Comment by mcanales2020** [comment]
Jae, según reglas de negocio al seleccionar cliente/site nos dirige a una pantalla de búsqueda de usuarios (se trae la información del artículo más sus estados), la cual para su correcto funcionamiento no podemos realizarla de modo offline. Esto fue comentado en reuniones.

**Comment by jyoo98** [comment]
Déjame consultar la documentación

**Comment by jyoo98** [comment]
Movimiento de artículos tampoco funciona offline
