### ISSUE TITLE
Yagan App: Error al generar una orden de trabajo con internet

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#250]
![image](https://github.com/mcanales2020/yagan/assets/131712561/67b134cd-1ddd-4055-9587-28dd8b426789)

Usuario: Operador, Administrador
la tratar de generar una orden de trabajo con internet da error.

**Comment by jyoo98** [comment]
Actualización: Ahora si realiza todo el proceso, pero no es reflejado en los reportes.

https://github.com/mcanales2020/yagan/assets/131712561/6e7d716a-675b-4f8c-8c4a-5a8bedc141ec

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado
