### ISSUE TITLE
Yagan App: Error en modulo entrega de artículos 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#252]
https://github.com/mcanales2020/yagan/assets/131712561/8897c153-06cc-47ce-8e99-bc08d4e19d2b

Al tratar de hacer una entrega, al leer los tags dice que el artículo ya esta vinculado a otro usuario, se probo con varios tags (no vinculados) y de igual manera salía el error.

Usuario: Administrador.

**Comment by jyoo98** [comment]
![image](https://github.com/mcanales2020/yagan/assets/131712561/583ac6bd-6fca-4059-bc7b-5938fa1cc2bf)

persiste el error.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado
