### ISSUE TITLE
Yagan App: Movimiento de artículos.

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#254]
https://github.com/mcanales2020/yagan/assets/131712561/d1638d0c-2b65-4968-92b3-87fc12b5502d

![image](https://github.com/mcanales2020/yagan/assets/131712561/177971de-82b7-4d8f-a7cf-e83a79a465e7)

Usuario: Administrador.

Tras finalizar un movimiento de artículo (guía de proceso), no se ve reflejado en el modulo de reportes.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
![image](https://github.com/mcanales2020/yagan/assets/131712561/7e1e0d2e-d807-416c-b7f0-2ea1b2429330)

Ahora aparece este mensaje.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado
