### ISSUE TITLE
Yagan Web: Error al editar usuario

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#258]
![image](https://github.com/mcanales2020/yagan/assets/131712561/ddd07492-cba8-4fcd-9467-4d2e005ff24d)

Usuario: Administrador.

Al editar un usuario, si dejo un dato en blanco no especifica porque no deja guardar y solo muestra un error.

**Comment by jyoo98** [comment]
Si dejo en blanco Cliente y/o Site da el mismo error no especificado

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Cuando dejo el código interno sigue saliendo el error inespecífico. Los demás funcionando correctamente.

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
