### ISSUE TITLE
Devolucion Zipper - No señala lo no devuelto en historial

### ISSUE THREAD

**Issue by jpfuhrer** [mcanales2020/yagan#26]
Se realizo primero una precarga de blusa (tag 1) a Zipper 400. Luego se realizo entrega de zipper, y descargo todo en guia de entrega. (aparece en historial clinico como con usuario). 

**Luego selecciono desde operador de ventanilla 1, el icono "Devolucion Zipper":**
![image](https://user-images.githubusercontent.com/125582822/222466378-4a8a4de5-3a19-4abe-92a8-6c36fce00f84.png)

Selecciono devolucion **"por usuario"** y escribo el nombre (**aun NO despliega las alternativas, hay que escribir nombre completo)**. Luego me aparece la ventana con el zipper, usuario:
![image](https://user-images.githubusercontent.com/125582822/222468054-90092587-1451-4537-8cc8-3b6a4849bd94.png)

- No aparece arriba que no ha devuelto la Blusa Blanca talla S (es porque fue entregada recien ??)
- Presiono **"Devolver Contenedor"**, y no lo agrega...

![image](https://user-images.githubusercontent.com/125582822/222468727-ef0a14de-af81-44ce-80f1-ce4f6f0364fb.png)

**Comment by jpfuhrer** [comment]
Zipper aparece en historial, con usuario

![image](https://user-images.githubusercontent.com/125582822/222469344-899e24b9-afa5-45e9-94d3-0e687e3c72b9.png)

**Comment by H-ADASME563** [comment]
El que no aparezca el artículo en la lista de los no devueltos es porque recién fue entregado

**Comment by jpfuhrer** [comment]
Y desde cuando debería aparecer entonces?

 



 

De: Henry Adasme López ***@***.***> 
Enviado el: lunes, 6 de marzo de 2023 12:16
Para: mcanales2020/yagan ***@***.***>
CC: jpfuhrer ***@***.***>; Author ***@***.***>
Asunto: Re: [mcanales2020/yagan] Devolucion Zipper - No ingresa el Zipper, no señala lo no devuelto en historial (Issue #26)

 

El que no aparezca el artículo en la lista de los no devueltos es porque recién fue entregado

**Comment by H-ADASME563** [comment]
Debería de aparecer en la lista de no entregados después de que hayan 24 de haber entregado el articulo y que este no haya sido devuelto

**Comment by jpfuhrer** [comment]
no aparece aun

**Comment by jpfuhrer** [comment]
Por validar pasadas 24 horas
