### ISSUE TITLE
Yagan Web: Error en botón completar entrega

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#260]
https://github.com/mcanales2020/yagan/assets/131712561/daffd61e-d70f-4e93-9b5b-6098d6a8812d

Usuario: Administrador, Operador.

Al realizar una GE o una OT y darle completar entrega, en el siguiente menú los botones de los biométricos no realizan ninguna acción, y también cabe mencionar que en el cliente nestle no tengo habilitado el reconocimiento facial. Finalmente al darle al botón cerrar da error.

![image](https://github.com/mcanales2020/yagan/assets/131712561/6ea6abb2-4ed0-45aa-9236-d980869cdf70)

![image](https://github.com/mcanales2020/yagan/assets/131712561/5baba06d-1cb2-4ce9-ac34-db057f950b47)

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
revisado
