### ISSUE TITLE
Yagan Web: Error al realizar una precarga

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#261]
https://github.com/mcanales2020/yagan/assets/131712561/4ab0ee6a-4cbe-4227-b268-38bd88d88973

Usuario: Operador Nes-vent1.

Al realizar un precarga, al darle al botón finalizar operación da error.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado
