### ISSUE TITLE
Yagan App: Error en asignación de artículos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#262]
![image](https://github.com/mcanales2020/yagan/assets/131712561/b402be25-5d45-4b62-970a-b7bb1c2fa393)

Usuario: Administrador.
Al realizar una asignación de artículos, al darle a leer, lee los tags encontrados, si le doy a reiniciar lee los leídos anteriormente aunque ya no estén en el rango de la antena del handheld.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado

**Comment by jyoo98** [comment]
Revisado
