### ISSUE TITLE
Yagan App: Error al configurar la potencia de la antena

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#263]
https://github.com/mcanales2020/yagan/assets/131712561/f4134281-b709-4d97-99de-9c472090aec5

Al tratar de configurar la potencia de la antena, si la pongo al mínimo, no se guarda, pero si lo pongo un poco mas alta si. Esto pasa solo cuando se pone al minimo.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado
