### ISSUE TITLE
Yagan App: Error al mostrar usuario en GE

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#265]
![image](https://github.com/mcanales2020/yagan/assets/131712561/645029be-2bf2-473b-b7c4-e98348a97d19)

Usuario: Administrador.

Al buscar un usuario por contenedor para realizar una GE, se muestra al usuario dos veces.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
![image](https://github.com/mcanales2020/yagan/assets/131712561/333aa448-4e60-4ad0-a8b0-6c897d3037c7)

Al buscar al usuario por el código especifico, aparecen mas usuarios.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado
