### ISSUE TITLE
Yagan App: No se reflejan los datos de las precargas en la web

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#266]
![image](https://github.com/mcanales2020/yagan/assets/131712561/cd14b6ec-1317-49e5-9483-04dda0f270b9)
![image](https://github.com/mcanales2020/yagan/assets/131712561/73107011-f1eb-483d-a664-30f7b55b3d84)

Al realizar una precarga en la app Yagan, no se ve reflejada en la web.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado
