### ISSUE TITLE
Yagan App: Error en consulta de artículos 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#267]
![image](https://github.com/mcanales2020/yagan/assets/131712561/43e59937-768f-4179-bbac-cd2b370b92cf)

Al realizar una consulta de artículos da el error mostrado en la imagen.

**Comment by mcanales2020** [comment]
Jae, favor me puedes enviar el código del tag para revisión.

**Comment by jyoo98** [comment]
no pasa exactamente con solo un tag, tampoco pasa todo el tiempo, mas bien de 5 lecturas aproximadamente una vez muestra el error. Las pruebas las hice bajo las mismas condiciones y circunstancias.

**Comment by mcanales2020** [comment]
Un solo tag que pase el problema porfa que jordan tiene problemas para probar ya que sus tag no tienen error....un solo tag que tenga el problema y nosotros podremos replicar el problema porfa

**Comment by jyoo98** [comment]
E2806894000050234C546C58 este es uno de los que da problemas en consulta de artículos, mencionar que este tag esta ingresado en el sistema y ya se hicieron otras pruebas con el.

**Comment by jyoo98** [comment]
También me paso al tratar de hacer picking
