### ISSUE TITLE
Yagan App: Error al buscar usuario en modulo entrega de artículos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#269]
![image](https://github.com/mcanales2020/yagan/assets/131712561/a2f109a3-91c2-4f57-a0a7-086d2e833b72)

Al buscar por código 12003, muestra una lista extensa  de usuarios y no solo el que se esta buscando.
Usuario: Administrador.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
Revisado
