### ISSUE TITLE
Yagan App: Error en movimiento de artículos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#271]
![image](https://github.com/mcanales2020/yagan/assets/131712561/3a873697-f403-4229-b01d-5abfaf3965c6)
![image](https://github.com/mcanales2020/yagan/assets/131712561/e114f4fe-f277-4976-9576-4363867add25)

Usuario: Administrador

Al realizar un movimiento de artículos, seleccionar el estado Costura/Lavanderia-Ropa Limpia en el siguiente paso se cambia a Lavanderia-Ropa sucia/Lavanderia-Ropa Limpia, por lo tanto se rompe la trazabilidad.

**Comment by mcanales2020** [comment]
Corregido

**Comment by jyoo98** [comment]
El problema persiste, y ahora da error y se cierra la aplicación.

https://github.com/mcanales2020/yagan/assets/131712561/5f882620-ad99-43b0-870f-db3be13c1c46

**Comment by jyoo98** [comment]
Revisado
