### ISSUE TITLE
Yagan Nestlé Macul: Error al eliminar un dispositivo reader

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#276]
![image](https://github.com/mcanales2020/yagan/assets/131712561/a21c5f98-44e4-4055-8b65-89c0d4ce5019)

Usuario: Administrador

Al tratar de eliminar un dispositivo reader da el error.

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
