### ISSUE TITLE
Yagan Web Nestlé: Importar usuarios por carga masiva permite repetir el código interno 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#278]
![image](https://github.com/mcanales2020/yagan/assets/131712561/cf55cfe5-273d-4dfa-9780-8ee69a6c3153)

 Usuario: Administrador 

Al importar usuarios por carga masiva, si agrego mas de un usuario con el mismo código interno el sistema lo acepta sin ningún tipo de aviso. En este caso se edito uno de los códigos, pero en el momento que se hizo la importación estaban ambos usuarios con el código 457.

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
