### ISSUE TITLE
Esta Enredado el tema de agregar articulos a los creados - Por ejemplo agregar un par de botas

### ISSUE THREAD

**Issue by jpfuhrer** [mcanales2020/yagan#28]
Solo tenemos 1 articulo adentro. blusa Blanca talla S con tag N° 1. Se hace muy enredado agregar los articulos, y mas dificil aun agregar las botas (que tienen codigo fisico, son pares y a veces pueden gtener tag).

**Comment by jpfuhrer** [comment]
crear importador y tambien poder ingresar tag manuales

**Comment by cbastiasv** [comment]
Importador funciona. Falta la validación del código físico único

**Comment by jpfuhrer** [comment]
Probar cargador con codigo fisico
