### ISSUE TITLE
Yagan Web Nestlé: Error de datos en vinculación 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#282]
![Imagen de WhatsApp 2024-04-30 a las 15 30 22_9574e976](https://github.com/mcanales2020/yagan/assets/131712561/dfdc0bbb-1222-4f48-94a5-cb8d3673af2e)

Usuario: Administrador

En Vinculación/desvinculación de artículos la fecha de creación se muestra con un formato erróneo

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
