### ISSUE TITLE
Yagan Web Nestlé: Error en las busquedas

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#283]
![Imagen de WhatsApp 2024-04-30 a las 15 47 36_b97cafea](https://github.com/mcanales2020/yagan/assets/131712561/55cfb562-303c-43e9-9705-5e57c0c5aa51)

Usuario: Administrador

En la pantalla de vinculación/desvinculación de artículos, los recuadros de búsqueda no funcionan correctamente

**Comment by cbastiasv** [comment]
Resuelto
