### ISSUE TITLE
Yagan Web Nestlé: no se puede tipiar la ñ

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#284]
![image](https://github.com/mcanales2020/yagan/assets/131712561/28206d95-d2b0-441b-85ef-ab28b9898680)

Usuario: Administrador

En la sección de agregar usuario, en nombre y apellido no permite tipiar la ñ.

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
