### ISSUE TITLE
Yagan App Nestlé: Error en búsqueda de artículos 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#290]
https://github.com/mcanales2020/yagan/assets/131712561/5c459fc4-8388-45be-ab77-9c74d6266803

Usuario: Administrador, Operador

En búsqueda de artículos cuando quiero buscar por atributos, primero en cliente aparece el site, y después si pongo un nombre de usuario (usuario prueba) no encuentra nada.

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
revisado
