### ISSUE TITLE
Yagan App Nestlé: Error en consulta de artículos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#291]
![image](https://github.com/mcanales2020/yagan/assets/131712561/5f17790d-f56b-490a-a6d2-a38dd0944fc9)

Usuario: Administrador, Operador

A veces da este error en movimiento de artículos y consulta de artículos, la potencia de la antena queda en -1 y no se puede cambiar, por lo que no lee nada

video pendiente

**Comment by cbastiasv** [comment]
Este es un problema en SDK que queda tomado e impide configurar la potencia, se agregó un mensaje señalando que se debe reiniciar la app o el equipo para solucionar.

**Comment by jyoo98** [comment]
https://github.com/mcanales2020/yagan/assets/131712561/89a6545b-2e89-420e-8be0-a085b5043d82

ahora no me deja cambiar la potencia
