### ISSUE TITLE
Yagan App Nestlé: Error al iniciar sesión

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#292]
https://github.com/mcanales2020/yagan/assets/131712561/6a7b2ecc-668e-4784-9b9d-080ca9c58b83

![image](https://github.com/mcanales2020/yagan/assets/131712561/ca6fc974-55e7-46be-a427-5774dc7ab764)

Usuario: Administrador, Operador

Estábamos haciendo una OT, cerré la aplicación y ya no inicia sesión.

**Comment by cbastiasv** [comment]
Es un problema del SDK que impide iniciar la PDA, para solucionar esto es necesario bien reiniciar la app o, en el peor de los casos, el handheld.

**Comment by jyoo98** [comment]
revisado
