### ISSUE TITLE
Yagan App Nestlé: Error en las operaciones 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#293]
https://github.com/mcanales2020/yagan/assets/131712561/4c5d4e73-b33e-4fbc-b521-1c240c0462cc

Usuario: Administrador, Operador

Al hacer una GE, OT, GP da error de sesión caducada. Se arregla eliminando los datos de almacenamiento de la app

**Comment by cbastiasv** [comment]
Sucede en los casos en que un mismo usuario inicia sesión en más de un handheld conectado al mismo servidor. El sistema está diseñado para que un usuario solo pueda iniciar sesión en un handheld a la vez. Aquí sucedió porque realicé pruebas a través de Postman y generé un token distinto al que estaba almacenado en el handheld. 
En estos casos es necesario cerrar sesión en la app e iniciar nuevamente la sesión.

**Comment by jyoo98** [comment]
Revisado
