### ISSUE TITLE
Yagan App Nestlé: Cierre de aplicación al cambiar la potencia de la antena

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#295]
https://github.com/mcanales2020/yagan/assets/131712561/23e8ce06-e54c-4792-be48-0f702cec4941

Usuario: Administrador, operador

En cualquier operación, cuando quiero regular la potencia la app se cierra inesperadamente

**Comment by cbastiasv** [comment]
Resuelto. 
Se añadió un delay (tiempo de espera) al momento de abrir el diálogo para configurar la potencia, esto para evitar que al intentar configurar la potencia la lectura de tags se encuentre aun en funcionamiento, lo que hace que falle el sdk y la app se cierre.
El delay es de 5 segundos.

**Comment by jyoo98** [comment]
Revisado
