### ISSUE TITLE
Yagan Web Nestlé: Error en Reportes Último estado Ítem 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#296]
https://github.com/mcanales2020/yagan/assets/131712561/8e5baf65-e826-44c3-b781-9e2580959f09

Usuario: Administrador, Operador

En Ultimo estado ítem, el buscador solo funciona con el parámetro nombre

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
