### ISSUE TITLE
Yagan Web Nestlé: Resumen Artículos Entregados

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#297]
![image](https://github.com/mcanales2020/yagan/assets/131712561/a899becd-5d35-4b0b-ab7b-ebb5a98cad48)

![image](https://github.com/mcanales2020/yagan/assets/131712561/887a49a4-7ca9-464d-99a6-ab62228e217a)

Usuario: Administrador, Operador

los gráficos mostrados deberían mostrar o solo poleras con detalle de color y talla y otro con pantalón con las mismas características, o solo un grafico que muestre poleras vs pantalones.

Por otra parte, en la lista, los artículos deberían aparecer agrupados por artículo. En la imagen aparecen varias veces el mismo artículo como si fueran distintos

**Comment by cbastiasv** [comment]
Resuelta la parte de la lista, el problema es que en el resumen tomaba en cuenta la hora de entrega.
En cuanto a los gráficos, estos están desarrollados de acuerdo con lo estipulado en el documento de requerimientos (SOW) y muestra los artículos entregados por Tipo de Artículo, un gráfico para cada tipo contra el total de artículos entregados. En el documento no fue solicitado separar por color y talla por lo que desarrollar esto es un control de cambios.

**Comment by jyoo98** [comment]
Revisado
