### ISSUE TITLE
Yagan Web Nestlé: Reporte Artículos no Devueltos 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#298]
![image](https://github.com/mcanales2020/yagan/assets/131712561/4dc9adb4-c486-4e63-915e-bfbf006c15ae)

Usuario: Administrador, Operador

Los gráficos deberían ser por tipo de artículo, en este caso uno para el artículo polera y que dentro especifique color y talla y cuantos no han sido devueltos y otro para pantalones con las mismas especificaciones .

**Comment by cbastiasv** [comment]
El documento de requerimientos (SOW) especifica que en el apartado de gráficos se debe mostrar uno por cada Tipo de Artículo. Modifiqué el reporte para que muestre todos los tipos de artículos agrupados sin importar la fecha (la versión anterior tomaba en cuanta le fecha, por ello se mostraban tantos gráficos).
El especificar el color y talla de los artículos no devueltos no estaba especificado en el SOW por lo que corresponde a un Control de Cambios.

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
