### ISSUE TITLE
Yagan Web Nestlé: Error en las fechas en reporte de artículos no devueltos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#299]
https://github.com/mcanales2020/yagan/assets/131712561/58c73e4c-c5dc-4f78-ab90-2621e9007319

Usuario: Administrador, Operador.

Al abrir el reporte debería aparecer el orden por fechas pero sale en desorden

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
