### ISSUE TITLE
Yagan App Teva: Error en búsqueda de usuario en guía de entrega

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#300]
https://github.com/mcanales2020/yagan/assets/131712561/031a4509-51f9-46f6-ab47-d9e218590ce4

Usuario: Administrador

En GE, al buscar un usuario por nombre si ingreso el apellido no busca coincidencias

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
