### ISSUE TITLE
Yagan App TEVA: Error en Vincular artículos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#301]
https://github.com/mcanales2020/yagan/assets/131712561/16d5fceb-266f-4930-8a9c-bc860e88c255

Usuario: Administrador 

En Vincular Artículos, me aparece como titulo Entrega de Artículos y al buscar un usuario por nombre si ingreso el apellido no busca coincidencias.

**Comment by cbastiasv** [comment]
Resuelto en lo que respecta a la búsqueda de usuarios por nombre

**Comment by jyoo98** [comment]
Revisado
