### ISSUE TITLE
Yagan App Nestlé: Error en movimiento de artículos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#302]
https://github.com/mcanales2020/yagan/assets/131712561/a28cf58b-c0d9-468b-a41a-ad902702ea37

Usuario: Administrador, Operador

Al realizar una lectura (1500 TAGs aprox.) en movimiento de artículos dice que "el tiempo de espera caduco". Con lecturas menores no pasa (menos de 200 TAGs aparox.)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
