### ISSUE TITLE
Yagan Web: Dos clicks para crear tallas

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#304]
![Imagen de WhatsApp 2024-06-27 a las 17 28 41_b0ced773](https://github.com/mcanales2020/yagan/assets/131712561/c55a46cb-ced0-4bcc-b9b4-a22f789e906a)
![Imagen de WhatsApp 2024-06-27 a las 17 28 53_6f4e4992](https://github.com/mcanales2020/yagan/assets/131712561/274e92a3-23d4-4569-9911-dfb88239ca38)
![Imagen de WhatsApp 2024-06-27 a las 17 28 59_b3bfc885](https://github.com/mcanales2020/yagan/assets/131712561/7cf47d1d-a5b3-4ea2-9785-b2cfcf8717a6)
![Imagen de WhatsApp 2024-06-27 a las 17 29 10_06031c66](https://github.com/mcanales2020/yagan/assets/131712561/9f0f14f9-070f-4253-8e01-75ed66805f58)

Usuario: Administrador 

Al crear tallas debo hacer dos clicks para poder guardar, debería ser con uno.

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
