### ISSUE TITLE
Yagan Web Nestlé: Los reportes tarden demasiado en cargar

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#305]
https://github.com/mcanales2020/yagan/assets/131712561/780426c5-5fe2-440d-89f1-b4400fe25fb4

![Imagen de WhatsApp 2024-06-28 a las 11 05 59_62c31f2a](https://github.com/mcanales2020/yagan/assets/131712561/d116b6b3-578d-41c6-a30e-2c787dab18f2)

Usuario: Administrador, Manager

Los reportes tardan demasiado en cargar, actualmente en Nestlé hay aprox. 5800 TAGS y aprox 50 tipos de artículos.

Los reportes que muestren movimiento o datos por tiempo seria mejor dejarlos para que predeterminadamente muestren movimientos o datos por día y no el total.

El video esta en velocidad x7

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
