### ISSUE TITLE
Yagan Web: Error al editar estados

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#306]
![Imagen de WhatsApp 2024-07-02 a las 14 59 55_9c021c93](https://github.com/mcanales2020/yagan/assets/131712561/f0e8401c-1ef4-4cd5-aed1-9f9e0f84a522)

Al editar estados dentro del flujo, aparece en blanco

![Imagen de WhatsApp 2024-07-02 a las 15 27 03_ce8c0aa2](https://github.com/mcanales2020/yagan/assets/131712561/5d975f7f-bc00-47b0-81f0-9ec8e524eeb4)

En el mantenedor de estados no aparecen todos los estados creados

Usuario: Administrador

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado

**Comment by jyoo98** [comment]
Revisado
