### ISSUE TITLE
Yagan Web Servidor central: Error en Artículos Enviados desde Sites Locales

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#308]
![image](https://github.com/user-attachments/assets/175a0973-a6f5-494d-8913-3a442a528849)

Usuario: administrador

En esta sección me esta mostrando datos de un cliente (Ariztia) que no esta registrado en el servidor central de pruebas.

**Comment by cbastiasv** [comment]
Los datos que aparecen eran del Servidor de QA de SPS, se eliminaron los registros y la conexión. Ahora se encuentra conectado el Servidor TEVA al servidor de pruebas de lavandería

**Comment by jyoo98** [comment]
Revisado
