### ISSUE TITLE
Yagan Web Servidor central de pruebas: Error al mostrar clientes y sites

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#309]
![Imagen de WhatsApp 2024-08-16 a las 11 13 53_99a8a536](https://github.com/user-attachments/assets/d6505582-5ab4-4835-a933-89fcec815976)

![Imagen de WhatsApp 2024-08-16 a las 11 14 01_6c5b8be7](https://github.com/user-attachments/assets/9c0156ad-1fb1-4fdd-a10d-d912029d06f5)

Usuario: Administrador

En toda sección en la que tenga que elegir servidores y sites, me aparece el cliente Teva con su site duplicados, esto pasa tanto en la web como en la app.

**Comment by cbastiasv** [comment]
En los reportes, los campos Cliente y Sites muestran todos los Clientes y Sites existentes en el sistema, aun cuando estos hubiesen sido deshabilitados. Existe más de un TEVA y MAIPÚ almacenado en la base de datos. Lo hace en los reportes para que siempre se tenga acceso a los datos de un cliente/site aun cuando este se hubiese deshabilitado en el sistema. Se puede quitar esto y que quede de la misma forma que el resto de los campos Cliente/Site.

**Comment by jyoo98** [comment]
Puedes borrar los que están repetidos de la base de datos? recuerdo que cuando estaba configurando eso creo que hacían falta unas librerías, entonces cuando le daba guardar no hacia nada pero en verdad si estaba guardando. Teva Maipú debería ser el correcto

**Comment by jyoo98** [comment]
Revisado
