### ISSUE TITLE
Yagan Web TEVA: Error en reporte Despachos desde Lavandería 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#311]
![image](https://github.com/user-attachments/assets/d85a88f8-61a5-4dcf-bf52-54c6df915f3b)

![image](https://github.com/user-attachments/assets/e3067257-0540-4989-b614-251c75c6246b)

Usuario: Administrador

Al hacer click en Despachos desde lavandería da error de servidor.

**Comment by cbastiasv** [comment]
Corregido en v2.7 (yagan_web_v2.7.zip)

**Comment by jyoo98** [comment]
Revisado
