### ISSUE TITLE
Yagan Web: No funciona la exportación de  artículos al servidor central

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#312]
![image](https://github.com/user-attachments/assets/c4f224df-60b2-457d-92c2-2e811e2fd12f)

![image](https://github.com/user-attachments/assets/11962b8c-a8a4-4904-a8b5-7643917ef618)

![image](https://github.com/user-attachments/assets/4e83de84-6071-4567-98fe-411a12680401)

![image](https://github.com/user-attachments/assets/183de87c-d7ff-4b98-8860-cccfa538dc43)

son 140 artículos aprox. que exporte desde teva al servidor central pero no se actualizan.

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
