### ISSUE TITLE
Yagan Web: Error al descargar grafico en pdf de inventario de artículos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#313]
![image](https://github.com/user-attachments/assets/037e79ae-8210-4017-89f6-a7db4c6f4f1e)

Al descargar el pdf del grafico de inventario de artículos, se descarga el de artículos no devueltos.

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
