### ISSUE TITLE
Yagan Web Teva: Resumen de movimiento de artículos

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#317]
![Imagen de WhatsApp 2024-10-29 a las 15 23 29_58c33b41](https://github.com/user-attachments/assets/dacfb5b0-d6bb-4076-967f-0d7b2dc8a784)

Usuario: Administrador

1.- muestra que la cantidad de movimientos de prendas no coincide con el numero realizados efectivamente por la lectura incluso supera la cantidad en stock de prendas de la base de datos, mientras mas atrás se va en la tabla sube sin control el conteo.

![Imagen de WhatsApp 2024-10-29 a las 15 25 32_b3f312ae](https://github.com/user-attachments/assets/c6d09d97-0667-43ea-acd1-a77b53083d2f)

mientras que el detalle del folio muestra 277 lecturas, afecta a la hora de descargar el csv con esos datos errores para realizar los resúmenes.

2.- a la hora de filtrar las tablas y proceder a descargar el cvs no se filtra por fechas solo descarga toda la tabla, queda como consulta si tengo 5 años de movimientos por no poder filtrar lo que quiero descargar la tabla se hará infinita puede conllevar a un error de descarga luego ?

**Comment by cbastiasv** [comment]
1. No pude replicar el error. En el servidor de pruebas la cantidad mostrada en yagan coincide con lo almacenado en la base de datos. Es probable que sea error en los datos almacenados pero no puedo acceder al servidor de teva a través de anydesk
2. Corregido en yagan web v2.9

**Comment by cbastiasv** [comment]
Corregido punto 1 con actualización api móvil (v1.6)

**Comment by jyoo98** [comment]
Revisado punto 1

**Comment by jyoo98** [comment]
Revisado punto 2
