### ISSUE TITLE
Yagan Web Teva: Resumen artículos entregados

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#319]
![Imagen de WhatsApp 2024-10-29 a las 15 27 14_61a000d6](https://github.com/user-attachments/assets/fda20020-918d-4743-b08f-a5298e96aad8)

aquí muestro los llaveros entregados en teva 292 unidades a la hora de pasarlo a la grafica por la misma fecha me muestra valores que no coinciden con las tablas

![Imagen de WhatsApp 2024-10-29 a las 15 28 34_eaa00f75](https://github.com/user-attachments/assets/a87fe057-8ea5-49b5-95d2-221964e391ba)

lo que no se refleja en los gráficos de torta 

Usuario: Administrador

**Comment by cbastiasv** [comment]
Corregido yagan web v2.9

**Comment by jyoo98** [comment]
Revisado
