### ISSUE TITLE
No permite crear articulo

### ISSUE THREAD

**Issue by asuarezLyon** [mcanales2020/yagan#4]
con , con punto o en blanco sale el mismo error

![image](https://user-images.githubusercontent.com/125581449/221229222-6556632d-06c3-44fe-9983-767829ee8c0e.png)

**Comment by asuarezLyon** [comment]
http://192.168.0.19:8080/Item/Create

**Comment by asuarezLyon** [comment]
No tira errror con punto , tira error con coma.

**Comment by H-ADASME563** [comment]
Corregido
