### ISSUE TITLE
PRIORIDADES - REUNION 15 MARZO

### ISSUE THREAD

**Issue by jpfuhrer** [mcanales2020/yagan#40]
1. PERMITIR MODIFICAR FLUJO (ELIMINAR ACCION Y GUARDAR)
2. PERMITIR TODAS LAS ACCIONES CON ANTENA 1 (LUEGO SE VERA HABILITAR LAS OTRAS ANTENAS)
3. BORRAR HISTORIALES PARA PARTIR DE 0

**Comment by cbastiasv** [comment]
Punto 3 Resuelto

**Comment by mcanales2020** [comment]
Punto 2 resuelto para las Operaciones de Ariztía
