### ISSUE TITLE
En operario vent1 en el boton abodega queda el boton de lectura en leyendo antes de iniciar

### ISSUE THREAD

**Issue by LgVitali** [mcanales2020/yagan#44]
![image](https://user-images.githubusercontent.com/125584994/226423588-5a20ad18-9713-443d-a4a8-abc5c71d2f9a.png)

http://192.168.0.19:8080/ProcessGuide/GenerateProcessGuide?IdCustomer=84&IdSite=47&IdItemState=8&IdActionWorkflow=12

**Comment by sebastianmtralcal** [comment]
Ok cerrar
