### ISSUE TITLE
En la precarga de zipper en boton de vent1 al iniciar la lectura emerge el error

### ISSUE THREAD

**Issue by LgVitali** [mcanales2020/yagan#46]
![image](https://user-images.githubusercontent.com/125584994/226424357-38c283d5-7bdf-4171-9d70-85e71317405d.png)

http://192.168.0.19:8080/Preload/GeneratePreload?IdCustomer=84&IdSite=47&IdDevice=1&IdItemState=6

**Comment by jyoo98** [comment]
Revisado
