### ISSUE TITLE
Problemas al Modificar Acciones

### ISSUE THREAD

**Issue by jpfuhrer** [mcanales2020/yagan#50]
Al parecer no los guarda correctametne. Estoy eliminando usuarios/reader en accion AR-BOI  para dejar solo a ropa limpia... pero en la practica esta sumando operadores..:

![image](https://user-images.githubusercontent.com/125582822/226429500-06758f20-d288-4ffb-b570-f895371d46e3.png)

**Comment by jpfuhrer** [comment]
O bien en la pagina principal (FLUJO), no actualiza correctamente...

**Comment by sebastianmtralcal** [comment]
Ok cerrar
