### ISSUE TITLE
Al repetir lectura de tag en vincular articulo deja ventana de error y la antena queda tomada

### ISSUE THREAD

**Issue by LgVitali** [mcanales2020/yagan#57]

**Comment by cbastiasv** [comment]
Especificar donde sucedió el problema (imagenes de la ventana)

**Comment by LgVitali** [comment]
![image](https://user-images.githubusercontent.com/125584994/230165406-4903d4b5-ced9-4453-ba89-2ba627d2c276.png)

**Comment by mcanales2020** [comment]
Resuelto
