### ISSUE TITLE
No Actualiza Nombre de atajo (dashboard) para operario AR-RLI

### ISSUE THREAD

**Issue by jpfuhrer** [mcanales2020/yagan#58]
Se modifico en acciones el atajo COSTURA con el nombre "Enviar a costura", para operario AR-RLI. Se guarda, pero al ingresar como ese operario (AR-RLI  / test), sigue apareciendo como COSTURA

![image](https://user-images.githubusercontent.com/125582822/226432298-efc258ee-45b2-4eb5-853b-03679ee720cb.png)

**Comment by jpfuhrer** [comment]
![image](https://user-images.githubusercontent.com/125582822/226432566-ac1f2b1f-68d3-43a5-8b18-291ddd3cc0ce.png)

**Comment by jpfuhrer** [comment]
Solucionado al agregar Operador desde esta ventana y no desde la "tuerca"

**Comment by jpfuhrer** [comment]
Sigue sin cambiar icono. Dice COSTURA, en vez de decir "ENVIAR A COSTURA"

**Comment by jpfuhrer** [comment]
Lo mismo pasa para operario ventanilla 1  (AR-VENT1), al modificar nombre de Icono ENTREGA DIRECTA  a  "ENTREGA DIRECTA (ropa)"

No lo cambia en escritorio:
![image](https://user-images.githubusercontent.com/125582822/226436910-94dc1da7-1ef0-4571-88db-e082e663b0b2.png)

![image](https://user-images.githubusercontent.com/125582822/226437088-b3121efc-dad5-418f-9248-5a33bbee1d90.png)

**Comment by sebastianmtralcal** [comment]
Ok Cerrar
