### ISSUE TITLE
En base a que ordena los iconos de dashboar??

### ISSUE THREAD

**Issue by jpfuhrer** [mcanales2020/yagan#60]
Como se ordenan los iconos (atajos)?  En base a que los ordena?

![image](https://user-images.githubusercontent.com/125582822/226434541-fe6210ec-7049-4bde-8fda-b957e02e2a8c.png)

**Comment by jpfuhrer** [comment]
ordenar por tipo de documento (para operarios)

**Comment by cbastiasv** [comment]
Corregido
