### ISSUE TITLE
Ingresando como Operador pude editar codigo fisico- subir archivo

### ISSUE THREAD

**Issue by jpfuhrer** [mcanales2020/yagan#62]
Entre como operador AR-BOT1  (botas), y logre modificar un codigo fisico, subiendo archivo desde el pc.... Esto no deberia estar permitido para el operador..

![image](https://user-images.githubusercontent.com/125582822/226685610-32cf3ec1-95d7-4c8f-ab73-85a04b6bad8c.png)

**Comment by cbastiasv** [comment]
Corregido
