### ISSUE TITLE
Entrega de Botas - Operador AR-BOT1  No puede entregar ingresando con numero de botas

### ISSUE THREAD

**Issue by jpfuhrer** [mcanales2020/yagan#63]
Me voy a entrega de botas, y en filtro ingreso el rack de botas jpf01
![image](https://user-images.githubusercontent.com/125582822/226686471-7b88a21b-5002-4419-96a7-a265a5981461.png)

Luego me lleva a la pagina intermedia que hace seleccionar antenas, y no me deja seleccionar... 

![image](https://user-images.githubusercontent.com/125582822/226686773-eb0476a8-bfec-4a04-af53-8401e950b15e.png)

Por tanto no puedo avanzar con la entrega

**Comment by jpfuhrer** [comment]
se debe ingresar el rack de botas con el codigo, y asi lo mostrara

**Comment by sebastianmtralcal** [comment]
Ok Cerrar
