### ISSUE TITLE
No aparece contenedor en orden de trabajo de Botas

### ISSUE THREAD

**Issue by jpfuhrer** [mcanales2020/yagan#65]
Al realizar una devolución de botas (cod. fisico **jpf01**) como administrador, me permite devolverlas y crea la OT, pero no aparece el contenedor en la columna... no se puede ver que devolvió

![image](https://user-images.githubusercontent.com/125582822/226689030-943f37fe-4ae9-4d13-ac1c-04c7c206f6c4.png)

**Comment by sebastianmtralcal** [comment]
REEMPLAZAR ID_ARTICULO POR EL COD.FISICO  (NOMBRE, COD.FISICO, TAG)

**Comment by cbastiasv** [comment]
Corregido
