### ISSUE TITLE
Ver Listado de TAGs en Asignar Artículos

### ISSUE THREAD

**Issue by cbastiasv** [mcanales2020/yagan#66]
Falta el desarrollo de Ver Listado TAG en Asignar Artículos, donde aparecen todos los RFID (TAGs) leídos.

<img width="685" alt="image" src="https://user-images.githubusercontent.com/91262348/230160892-449c896c-14b7-43ba-bcb2-b0724726ad9d.png">

**Comment by mcanales2020** [comment]
Resuelto
