### ISSUE TITLE
Antenas no funcionan

### ISSUE THREAD

**Issue by asuarezLyon** [mcanales2020/yagan#7]
Antenas no operativas.

**Comment by jpfuhrer** [comment]
funciona antena ventanilla 1, faltan las otras

**Comment by jpfuhrer** [comment]
sigue funcionando solo antena 1

**Comment by mcanales2020** [comment]
Resuelto

**Comment by jpfuhrer** [comment]
pendiente, reunion el Lunes 17 en bilbao

**Comment by mcanales2020** [comment]
Resulto para Operaciones de Ariztía
