### ISSUE TITLE
Al finalizar permanece en misma pantalla.

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#71]
http://192.168.0.19:8080/Item/AssignItem2?IdItem=7

![image](https://user-images.githubusercontent.com/131712561/234106132-89885d88-0bda-4e17-9b12-7335fd78cd0f.png)

Usuario: Administrador
Al realizar asignación y lectura exitosa de tags, no vuelve a menu anterior y queda tomada la antena 4.
Al cancelar la operación vuelve a menu anterior, pero sí graba los tags leídos y apaga luz antena 4.

**Comment by mcanales2020** [comment]
Resuelto

**Comment by jyoo98** [comment]
Se queda en la misma pantalla

**Comment by mcanales2020** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
