### ISSUE TITLE
Al cancelar en Guia de Entrega sale error

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#72]
http://192.168.0.19:8080/DeliveryGuide/ShowDeliveryGuidesNew

![image](https://user-images.githubusercontent.com/131712561/234109738-6efe15f7-bff1-4bd9-a310-8809b4a5386b.png)

**Comment by cbastiasv** [comment]
RESUELTO

**Comment by jyoo98** [comment]
Revisado y solucionado
