### ISSUE TITLE
Al tratar de agregar una talla que no esta registrada, no la agrega y dice que ya existe

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#85]
http://192.168.0.19:8080/Size/Sizes
![image](https://user-images.githubusercontent.com/131712561/234395956-e0328c7a-32f1-4d08-826f-2a100eb46271.png)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado

**Comment by jyoo98** [comment]
![image](https://user-images.githubusercontent.com/131712561/235172919-cb19aea1-0026-4898-b4af-a30dbd3821f4.png)
Usuario: Administrador

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
