### ISSUE TITLE
Al ingresar datos en los recuadros nombre, rut, código interno y contenedor, al presionar buscar sale error

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#89]
http://192.168.0.19:8080/WorkOrder/GenerateWOUserNew?IdCustomer=84&IdSite=47&Message=Error%3A%20se%20encontro%20mas%20de%20una%20coincidencia%20por%20Rut%20Consultado.&IdItemState=2
![image](https://user-images.githubusercontent.com/131712561/234592636-5fd197be-df60-452d-baed-316911b27f8e.png)
Usuario: Operador ropa sucia

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
