### ISSUE TITLE
Al entregar Zipper 400 Precargado con una blusa S aparece pagina de error

### ISSUE THREAD

**Issue by jpfuhrer** [mcanales2020/yagan#9]
![image](https://user-images.githubusercontent.com/125582822/221589444-8769d189-afd3-401f-93db-9cade8593c14.png)

**Comment by jpfuhrer** [comment]
El mensaje aparece al presionar FINALIZAR, luego de marcar entrega de contenedor. No asi al presionar realizar la entrega, pero esta ultima no queda registrado como movimiento...  Tampoco reporta por defecto a entrega de zipper, para poder seguir entregando (hay que seleccionar contenedor nuevamente)

**Comment by asuarezLyon** [comment]
NON ISSUE, estaban tyrabajando en el servidor.
