### ISSUE TITLE
Al ingresar datos en los recuadros nombre, rut, código interno y contenedor, al presionar buscar sale error

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#90]
http://192.168.0.19:8080/WorkOrder/GenerateWOUserNew?IdCustomer=84&IdSite=47&IdDevice=1&Message=Error%3A%20se%20encontro%20mas%20de%20una%20coincidencia%20por%20Codigo%20interno%20consultado%20Consultado.&IdItemState=6
![image](https://user-images.githubusercontent.com/131712561/234594628-ffa98303-5b03-4b36-aaf6-15a070e60615.png)
Usuario: Operador Botas

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Al buscar por nombre y rut me redirige a otra pantalla y pide nuevamente los datos de validación.
Por codigo interno y contenedor funciona correctamente
![image](https://user-images.githubusercontent.com/131712561/235187046-4f4e2289-0cf0-44c1-a766-5bf847485735.png)

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
