### ISSUE TITLE
Despues de leer y asignar el tag, al finalizar operación sale error

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#96]
http://192.168.0.19:8080/DeliveryGuide/ShowDeliveryGuidesNew
![image](https://user-images.githubusercontent.com/131712561/234699308-17b72255-0b2a-48c9-bcd2-34fb8cbcc263.png)

**Comment by mcanales2020** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
