### ISSUE TITLE
Boton cancelar operacion no realiza ni una acción

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#97]
http://192.168.0.19:8080/StateItem/StateItem
![image](https://user-images.githubusercontent.com/131712561/234874680-64043d64-9df9-41e4-8b0c-a86803c94a46.png)
Usuario: Manager
al tratar de cancelar la operación, el boton cancelar operación no realiza ni una acción.

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
Revisado
