### ISSUE TITLE
Boton eliminar articulo vinculado al usuario no realiza ni una acción 

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#98]
http://192.168.0.19:8080/SizeUser/SizeUsers/6
![image](https://user-images.githubusercontent.com/131712561/235160484-107f481c-8373-4107-8d86-dc9fa504eb48.png)
Usuario: Administrador

**Comment by jyoo98** [comment]
Esto pasa solo cuando se vincula un nuevo articulo, al ir a la lista de usuarios y abrir nuevamente la configuración funciona normal

**Comment by cbastiasv** [comment]
Resuelto
