### ISSUE TITLE
Despues de agregar un articulo a un usuario, al guardar se queda en la misma pantalla

### ISSUE THREAD

**Issue by jyoo98** [mcanales2020/yagan#99]
http://192.168.0.19:8080/SizeUser/SizeUsers/6
![image](https://user-images.githubusercontent.com/131712561/235161614-fea3127a-f632-4127-bc1b-71a51292a4ef.png)
Usuario: Administrador

**Comment by cbastiasv** [comment]
Resuelto

**Comment by jyoo98** [comment]
¿El boton guardar fue eliminado?

**Comment by cbastiasv** [comment]
Si, ahora se guarda al presionar Agregar Artículo, no necesitas presionar el guardar

**Comment by jyoo98** [comment]
Ok, revisado
